---
title: "Impute and partition data"
author: "Sam Majumder"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### choose the file "Sunflower"

### IMPUTE THE DATA ### 

data <- read.csv("Sunflower.csv")

######

## converting the Species column into a factor ####

data$Species <- factor(data$Species)

### converting the data as "." to NA values 

data[data=="."] <- NA

### Converting all character columns as numeric ##

library(tidyverse)

data <- data %>% mutate_if(is.character,as.numeric)



### create partition in the dataset ## train and test ###

library(lattice)
library(ggplot2)
library(caret)

s <- createDataPartition(y=data$Species, p=0.70, list = F)
train <- data[s,]
test <- data[-s,]

### Imputing data by rfImpute #### 

library(randomForest)

train_imputed <- rfImpute(Species~., data = train)
test_imputed <- rfImpute(Species~., data = test)

### writing out the imputed files ### 

## train

write.csv(train_imputed,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_2/train_imputed.csv")

## test### 

write.csv(test_imputed,"D:/Drive_C_2_18_21/PhD_WORK/Chapter_2/test_imputed.csv")

```


